import type { NextPage, GetServerSideProps } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import { runContract } from "../utils/runContract";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [nStrContactValue, setNStrContactValue] = useState<null | string>(null);
  const [nStrError, setnStrError] = useState<null | string>(null);

  useEffect(() => {
    runContract()
      .then((strValue) => {
        setNStrContactValue(strValue);
        setnStrError(null);
      })
      .catch((err) => {
        setNStrContactValue(null);
        setnStrError("Failed to get contract value");
      });
  }, []);

  const displayContract = () => {
    if (!!nStrError) return <p style={{ color: "red" }}>{nStrError}</p>;
    if (!!nStrContactValue) {
      return (
        <p>
          Contract value: <b>{nStrContactValue}</b>{" "}
        </p>
      );
    }

    return <p>No data</p>;
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Hardhat Ethereum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Hardhat Ethereum demo</h1>
        <div>{displayContract()}</div>
      </main>
    </div>
  );
};

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   let strContractValue = "No value";

//   try {
//     strContractValue = await runContract();
//   } catch (error) {
//     strContractValue = "Failed to get contract value";
//   }
//   return {
//     props: { strContractValue },
//   };
// };

export default Home;
